import React,{useMemo,useState} from 'react';
import {useNavigate} from 'react-router-dom';
import {supabase} from './lib/supabase';

const read=(key,fallback)=>{try{const v=localStorage.getItem(key);return v===null?fallback:v}catch{return fallback}};
const write=(key,value)=>{try{localStorage.setItem(key,value);return true}catch{return false}};
const publishedEvents=data=>(Array.isArray(data.events)?data.events:[]).filter(e=>e.published&&!e.archived).sort((a,b)=>`${a.date} ${a.start||''}`.localeCompare(`${b.date} ${b.start||''}`));
const slug=s=>String(s||'jyc').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const fmt=d=>{try{return new Date(`${d}T12:00:00`).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}catch{return d||'Date TBA'}};
const eventState=e=>{const now=Date.now();const start=new Date(`${e.date}T${e.start||'00:00'}:00`).getTime();const end=new Date(`${e.date}T${e.end||e.start||'23:59'}:00`).getTime();if(Number.isNaN(start))return 'upcoming';if(now<start)return 'upcoming';if(now<=end)return 'live';return 'past'};

export function MomentsPage({data}){
 const nav=useNavigate();
 const items=(data.gallery||[]).filter(x=>x.url);
 const groups=useMemo(()=>{const m=new Map();items.forEach(x=>{const k=x.association||x.album||x.type||'JYC';if(!m.has(k))m.set(k,[]);m.get(k).push(x)});return [...m.entries()]},[items]);
 return <section className="section page final-platform-page moments-page"><div className="final-page-head reveal"><span className="eyebrow">JYC MOMENTS</span><h1>Real moments. Real campus.</h1><p>An editorial archive built from photographs actually published by JYC. No synthetic filler.</p><div className="page-stat-row"><span><b>{items.length}</b> moments</span><span><b>{groups.length}</b> collections</span></div></div>{items.length?<><div className="moments-feature-grid">{items.slice(0,3).map((x,i)=><button key={x.id||i} className={`moments-feature moments-feature-${i} tilt-card`} onClick={()=>nav('/gallery')}><img src={x.url} alt={x.caption||'JYC moment'} loading="lazy"/><span><small>{x.association||'JYC'}</small><strong>{x.caption||'Campus moment'}</strong></span></button>)}</div><div className="moments-collections">{groups.map(([name,arr])=><article key={name} className="moment-collection reveal"><div><span className="eyebrow">COLLECTION</span><h2>{name}</h2><p>{arr.length} published moment{arr.length===1?'':'s'}.</p></div><div className="moment-strip">{arr.slice(0,4).map((x,i)=><button key={x.id||i} onClick={()=>nav('/gallery')}><img src={x.url} alt={x.caption||name} loading="lazy"/></button>)}</div></article>)}</div></>:<div className="final-empty"><span className="eyebrow">VISUAL ARCHIVE</span><h2>The archive is waiting for its first published moments.</h2><p>Once JYC uploads official photography, this page becomes the visual memory of the campus.</p><button className="btn secondary" onClick={()=>nav('/gallery')}>Open Gallery →</button></div>}</section>
}

function makeICS(events){
 const esc=v=>String(v||'').replace(/([,;\\])/g,'\\$1').replace(/\n/g,'\\n');
 const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');
 const rows=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//JYC//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH'];
 events.forEach(e=>{const start=new Date(`${e.date}T${e.start||'00:00'}:00`);const end=new Date(`${e.date}T${e.end||e.start||'23:59'}:00`);if(Number.isNaN(start.getTime()))return;const iso=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');rows.push('BEGIN:VEVENT',`UID:${esc(e.id)}@jyc128`,`DTSTAMP:${stamp}`,`DTSTART:${iso(start)}`,`DTEND:${iso(end)}`,`SUMMARY:${esc(e.title)}`,`LOCATION:${esc(e.venue)}`,`DESCRIPTION:${esc(e.description)}`,'END:VEVENT')});rows.push('END:VCALENDAR');return rows.join('\r\n');
}
function downloadText(name,text,type){const blob=new Blob([text],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function googleCalendarUrl(e){const d=new Date(`${e.date}T${e.start||'00:00'}:00`),end=new Date(`${e.date}T${e.end||e.start||'23:59'}:00`);if(Number.isNaN(d.getTime()))return '#';const iso=x=>x.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(e.title||'JYC Event')}&dates=${iso(d)}/${iso(end)}&details=${encodeURIComponent(e.description||'')}&location=${encodeURIComponent(e.venue||'')}`}

export function AgendaPage({data}){
 const nav=useNavigate();
 const events=publishedEvents(data);
 const [tick,setTick]=useState(0);
 const saved=events.filter(e=>read(`jyc-saved-event-${e.id}`,'')==='1');
 const reminders=events.filter(e=>read(`jyc-reminder-${e.id}`,'')==='1');
 const toggleReminder=e=>{const k=`jyc-reminder-${e.id}`;if(read(k,'')==='1')localStorage.removeItem(k);else write(k,'1');setTick(x=>x+1)};
 const clearAll=()=>{saved.forEach(e=>localStorage.removeItem(`jyc-saved-event-${e.id}`));setTick(x=>x+1)};
 const downloadAll=()=>{if(!saved.length)return;downloadText('jyc-my-jyc-agenda.ics',makeICS(saved),'text/calendar;charset=utf-8')};
 return <section className="section page final-platform-page agenda-page"><div className="final-page-head reveal"><span className="eyebrow">MY JYC · AGENDA</span><h1>Your campus, your schedule.</h1><p>Saved events become a lightweight personal agenda. Nothing here replaces an official registration.</p></div><div className="agenda-actions reveal"><button className="btn" disabled={!saved.length} onClick={downloadAll}>Download agenda .ics</button><button className="btn secondary" disabled={!saved.length} onClick={clearAll}>Clear saved events</button><span className="agenda-count"><b>{saved.length}</b> saved · <b>{reminders.length}</b> reminders</span></div>{saved.length?<div className="agenda-list">{saved.map(e=><article className="agenda-row reveal" key={e.id}><div className="agenda-date"><b>{new Date(`${e.date}T12:00:00`).getDate()}</b><span>{new Date(`${e.date}T12:00:00`).toLocaleDateString('en-IN',{month:'short'})}</span></div><div className="agenda-copy"><span className={`agenda-state ${eventState(e)}`}>{eventState(e).toUpperCase()}</span><h3>{e.title}</h3><p>{fmt(e.date)} · {e.start||'Time TBA'} · {e.venue||'Venue TBA'}</p><small>{e.club||'JYC'}</small></div><div className="agenda-row-actions"><button onClick={()=>nav('/events/'+e.id)}>Open</button><a href={googleCalendarUrl(e)} target="_blank" rel="noopener noreferrer">Google Calendar ↗</a><button className={read(`jyc-reminder-${e.id}`,'')==='1'?'active':''} onClick={()=>toggleReminder(e)}>{read(`jyc-reminder-${e.id}`,'')==='1'?'Reminder on':'Remind me'}</button></div></article>)}</div>:<div className="final-empty"><span className="eyebrow">YOUR AGENDA</span><h2>Nothing saved yet.</h2><p>Save an event from the Events page and it will appear here.</p><button className="btn secondary" onClick={()=>nav('/events')}>Explore events →</button></div>}<div className="platform-note reveal"><strong>Privacy by default</strong><span>Saved events and reminder preferences are stored on this device. Account registrations remain in JYC's protected data layer.</span></div></section>
}

export function ProjectsPage({data}){
 const nav=useNavigate();
 const projects=(data.clubs||[]).filter(c=>c.published).flatMap(c=>(Array.isArray(c.projects)?c.projects:[]).map((p,i)=>typeof p==='string'?{name:p,club:c.name,clubId:c.id}:({...p,club:p.club||c.name,clubId:c.id,key:p.id||`${c.id}-${i}`})));
 return <section className="section page final-platform-page projects-page"><div className="final-page-head reveal"><span className="eyebrow">JYC PROJECTS</span><h1>What students build.</h1><p>A public index of projects published through JYC club profiles.</p></div>{projects.length?<div className="project-grid">{projects.map((p,i)=><article className="project-card tilt-card reveal" key={p.key||i}><span className="project-index">{String(i+1).padStart(2,'0')}</span><small>{p.club||'JYC'}</small><h3>{p.name||p.title||'Published project'}</h3><p>{p.description||p.summary||'A project published by a JYC community.'}</p>{p.link&&/^https?:\/\//i.test(p.link)&&<a href={p.link} target="_blank" rel="noopener noreferrer">Open project ↗</a>}<button onClick={()=>nav('/clubs/'+p.clubId)}>Open club →</button></article>)}</div>:<div className="final-empty"><span className="eyebrow">PROJECT ARCHIVE</span><h2>No published projects yet.</h2><p>Projects will appear automatically when a published club adds them to its public profile.</p><button className="btn secondary" onClick={()=>nav('/clubs')}>Explore clubs →</button></div>}</section>
}


export function ProjectSubmissionPage(){
 const nav=useNavigate();
 const [form,setForm]=useState({name:'',description:'',link:'',club:'',submitter:'',email:''});
 const [busy,setBusy]=useState(false); const [status,setStatus]=useState('');
 const update=(k,v)=>setForm(x=>({...x,[k]:v}));
 const submit=async e=>{e.preventDefault();setStatus('');if(!form.name.trim()||!form.description.trim()||!form.submitter.trim()||!form.email.trim()){setStatus('Please complete the required fields.');return}
  if(form.link.trim()&&!/^https?:\/\//i.test(form.link.trim())){setStatus('Project link must start with http:// or https://.');return}
  setBusy(true);try{const {data:result,error}=await supabase.functions.invoke('public-submission',{body:{type:'project',name:form.name.trim(),description:form.description.trim(),link:form.link.trim()||'',club:form.club.trim()||'',submitter:form.submitter.trim(),email:form.email.trim().toLowerCase(),website:''}});if(error||!result?.ok)throw error||new Error(result?.error||'Could not submit the project.');setForm({name:'',description:'',link:'',club:'',submitter:'',email:''});setStatus('Submitted. JYC admins will review it before anything becomes public.')}catch(err){setStatus(err?.message||'Could not submit the project. Please try again.')}finally{setBusy(false)}};
 return <section className="section page final-platform-page project-submit-page"><div className="final-page-head reveal"><span className="eyebrow">OPEN SUBMISSION</span><h1>Put your work on the JYC map.</h1><p>Anyone in the JIIT community can submit a student project. Nothing is published automatically — a JYC administrator reviews every submission first.</p></div><div className="project-submit-layout reveal"><form className="project-submit-form" onSubmit={submit}><label><span>Project name *</span><input value={form.name} onChange={e=>update('name',e.target.value)} placeholder="e.g. Campus navigation app" required/></label><label><span>What did you build? *</span><textarea value={form.description} onChange={e=>update('description',e.target.value)} placeholder="Tell JYC what problem it solves, what you built and who worked on it." rows="7" required/></label><div className="form-grid"><label><span>Project / demo link</span><input value={form.link} onChange={e=>update('link',e.target.value)} placeholder="https://github.com/..."/></label><label><span>Club / society (optional)</span><input value={form.club} onChange={e=>update('club',e.target.value)} placeholder="If you built it with a JYC club"/></label></div><div className="form-grid"><label><span>Your name *</span><input value={form.submitter} onChange={e=>update('submitter',e.target.value)} placeholder="Your name" required/></label><label><span>Email *</span><input type="email" value={form.email} onChange={e=>update('email',e.target.value)} placeholder="you@example.com" required/></label></div>{status&&<div className={status.startsWith('Submitted.')?'success-box':'error-box'} role="status">{status}</div>}<div className="project-submit-actions"><button className="btn" disabled={busy}>{busy?'Sending for review…':'Submit for admin review →'}</button><button type="button" className="btn secondary" onClick={()=>nav('/projects')}>Back to projects</button></div></form><aside className="project-submit-info"><span className="eyebrow">HOW IT WORKS</span><h3>Simple. Human-reviewed.</h3><div><b>01</b><span>Submit your project and contact details.</span></div><div><b>02</b><span>JYC admins check the content and link.</span></div><div><b>03</b><span>Admin assigns it to the right club or JYC space.</span></div><div><b>04</b><span>Approved projects become public in the archive.</span></div><p>We do not publish your email or private submission details on the public site.</p></aside></div></section>
}

export function AchievementsPage({data}){
 const nav=useNavigate();
 const achievements=(data.clubs||[]).filter(c=>c.published).flatMap(c=>(Array.isArray(c.achievements)?c.achievements:[]).map((a,i)=>typeof a==='string'?{title:a,club:c.name,clubId:c.id}:({...a,club:a.club||c.name,clubId:c.id,key:a.id||`${c.id}-${i}`})));
 return <section className="section page final-platform-page achievements-page"><div className="final-page-head reveal"><span className="eyebrow">JYC ACHIEVEMENTS</span><h1>Proof of participation.</h1><p>Published milestones, wins and accomplishments from JYC communities.</p></div>{achievements.length?<div className="achievement-list">{achievements.map((a,i)=><article className="achievement-row reveal" key={a.key||i}><span>{String(i+1).padStart(2,'0')}</span><div><small>{a.club||'JYC'}</small><h3>{a.title||a.name||'Achievement'}</h3><p>{a.description||a.detail||'Published JYC achievement.'}</p></div><button onClick={()=>nav('/clubs/'+a.clubId)}>View club →</button></article>)}</div>:<div className="final-empty"><span className="eyebrow">ACHIEVEMENT ARCHIVE</span><h2>No published achievements yet.</h2><p>Official achievements will appear as clubs publish them.</p></div>}</section>
}

export function ExperienceSettings({onThemeChange}){
 const [lite,setLite]=useState(()=>read('jyc-performance','auto'));
 const [motion,setMotion]=useState(()=>read('jyc-motion','system'));
 const applyLite=v=>{setLite(v);write('jyc-performance',v);document.documentElement.dataset.performance=v==='auto'?(Boolean(navigator.connection?.saveData||((navigator.deviceMemory||8)<4))?'lite':'full'):v};
 const applyMotion=v=>{setMotion(v);write('jyc-motion',v);document.documentElement.dataset.motion=v};
 return <section className="section page final-platform-page settings-page"><div className="final-page-head reveal"><span className="eyebrow">EXPERIENCE SETTINGS</span><h1>Make JYC feel right on your device.</h1><p>Choose how much motion and visual processing the public experience should use. These settings stay on this device.</p></div><div className="settings-grid"><div className="settings-card"><span className="eyebrow">PERFORMANCE</span><h3>Visual quality</h3><div className="settings-options">{[['auto','Auto'],['full','Full experience'],['lite','Lite mode']].map(([v,l])=><button className={lite===v?'active':''} key={v} onClick={()=>applyLite(v)}>{l}<small>{v==='auto'?'Adapts to your device':'Always use this profile'}</small></button>)}</div></div><div className="settings-card"><span className="eyebrow">MOTION</span><h3>Animation preference</h3><div className="settings-options">{[['system','System default'],['full','Motion on'],['reduce','Reduce motion']].map(([v,l])=><button className={motion===v?'active':''} key={v} onClick={()=>applyMotion(v)}>{l}<small>{v==='reduce'?'Minimizes non-essential movement':'Use the selected motion level'}</small></button>)}</div></div></div><div className="platform-note reveal"><strong>Accessibility</strong><span>JYC also respects the browser's prefers-reduced-motion setting. Motion never carries essential information.</span></div></section>
}
